### ISSUE TITLE
v3.0 public discussions? 

### ISSUE THREAD

**Issue by slinstj** [yiisoft/core#3]
I have seen all the moves and new repos being created for Yii v3.0 and would like to know more about the discussions that are happening so that I can learn deeper about Yii structure and the motivations for each decision. It will give me conditions to contribute better in the future and will improve my Yii and OOP knowledges.

So, is there any public online places where those things are being planned and any developper would be welcome to "watch" or maybe participate in?

Thank you.

**Comment by hiqsol** [comment]
All the currently going changes are in very early stage of development.
So at the moment it's more just ongoing experiments.

The roadmap will be available soon.
Week or two maximum.
And then open discussion will start.

**Comment by tecnoterabyte** [comment]
You should eliminate the prefix yii to yii-console and yii-web and rename them console, and web, like the other repositories, maintaining the same standard.

**Comment by hiqsol** [comment]
@tecnoterabyte Not exactly. 

The idea is to name `yii-something` all the packages that require yii (`yiisoft/core`).
And `something` - packages that don't require `yiisoft/core` and can be used separately.

So: di, log, cache, rbac and core.
But: yii-web, yii-console, yii-debug and so on.

At the moment only the `yiisoft/di` is really actually `yiisoft/core` free.
Other packages will be made independent of `yiisoft/core` later.

**Comment by tecnoterabyte** [comment]
It would also be interesting that in the composer.json of the extensions it is changed from:

` "type": "yii2-extension" ---> "type": "yii-extension"
`

as the name of the frame yii, so no version is referenced.

**Comment by hiqsol** [comment]
Thanks to everyone for your interest!

Here is the Yii 3.0 changes outline:
https://github.com/yiisoft/core/blob/master/UPGRADE.md

Please note it's still under heavy development and subjected to change.

The application template you can start from will be available soon.

Announcement and invitation to participate in development will be made soon, after minimal stabilization.
At the moment discussion is welcome.

This issue is closed.
Please create new issues in this repository with your questions and proposals.
